/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wi.go.jim;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author RAFLI
 */
public class Jadwal extends javax.swing.JFrame {

    /**
     * Creates new form Jadwal
     */
    private static final String DB_URL = "jdbc:mysql://localhost/tubespbo";
    private static final String USER = "root";
    private static final String PASS = "";

    private static Connection conn;
    private static Statement stmt;
    private static ResultSet rs;
    private String selectedJadwalTersedia;
    private String selectedJadwalUser;
    private static int bookedJadwal = 0;

    /**
     * Creates new form NewJFrame
     */
    public Jadwal() {
        initComponents();
        try {
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
        } catch (SQLException ex) {
            ex.getMessage();
        }
        bookingJadwalButton.setVisible(false);
        deleteButton.setVisible(false);
        jadwalTerbookingFill.setText(Integer.toString(bookedJadwal));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void loadJadwalTersedia() {
        try {
            String query = "SELECT * FROM dbjadwal";
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            DefaultListModel<String> model = new DefaultListModel<>();
            while (rs.next()) {
                model.addElement(rs.getString("name"));
            }
            listJadwalTersedia.setModel(model);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void loadJadwalUser() {
        try {
            String query = "SELECT * FROM dbjadwaluser";
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            DefaultListModel<String> model = new DefaultListModel<>();
            while (rs.next()) {
                model.addElement(rs.getString("name"));
            }
            listJadwalUser.setModel(model);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listJadwalTersedia = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listJadwalUser = new javax.swing.JList<>();
        labelNama = new javax.swing.JLabel();
        labelTrainer = new javax.swing.JLabel();
        labelTingkat = new javax.swing.JLabel();
        labelDurasi = new javax.swing.JLabel();
        labelJam = new javax.swing.JLabel();
        namaFill = new javax.swing.JLabel();
        pelatihFill = new javax.swing.JLabel();
        tingkatFill = new javax.swing.JLabel();
        durasiFill = new javax.swing.JLabel();
        jamFill = new javax.swing.JLabel();
        perbaruiDaftarButton = new javax.swing.JButton();
        bookingJadwalButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelCustome2 = new Custome.PanelCustome();
        jButton2 = new javax.swing.JButton();
        buttonMaps = new javax.swing.JButton();
        buttonSchedule = new javax.swing.JButton();
        buttonGoals = new javax.swing.JButton();
        buttonTrainGuide = new javax.swing.JButton();
        jadwalTerbooking = new javax.swing.JLabel();
        jadwalTerbookingFill = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1400, 920));

        listJadwalTersedia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listJadwalTersediaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listJadwalTersedia);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Jadwal Tersedia", jPanel1);

        listJadwalUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listJadwalUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listJadwalUser);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Jadwal Terbooking", jPanel2);

        labelNama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNama.setText("Nama :");

        labelTrainer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTrainer.setText("Pelatih :");

        labelTingkat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTingkat.setText("Tingkat Kesulitan :");

        labelDurasi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelDurasi.setText("Durasi :");

        labelJam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelJam.setText("Jam Mulai:");

        namaFill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        pelatihFill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tingkatFill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        durasiFill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jamFill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        perbaruiDaftarButton.setText("Perbarui Daftar");
        perbaruiDaftarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perbaruiDaftarButtonMouseClicked(evt);
            }
        });

        bookingJadwalButton.setText("Booking Jadwal");
        bookingJadwalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingJadwalButtonMouseClicked(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Logo.jpg"))); // NOI18N
        jLabel5.setText("LOGO");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        panelCustome2.setBackground(new java.awt.Color(255, 255, 255));
        panelCustome2.setRoundBottomLeft(40);
        panelCustome2.setRoundTBottomRight(40);
        panelCustome2.setRoundTopLeft(40);
        panelCustome2.setRoundTopRight(40);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jButton2.setText("Rudi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCustome2Layout = new javax.swing.GroupLayout(panelCustome2);
        panelCustome2.setLayout(panelCustome2Layout);
        panelCustome2Layout.setHorizontalGroup(
            panelCustome2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustome2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButton2)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelCustome2Layout.setVerticalGroup(
            panelCustome2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        buttonMaps.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        buttonMaps.setText("Maps");
        buttonMaps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMapsActionPerformed(evt);
            }
        });

        buttonSchedule.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        buttonSchedule.setText("Schedule");
        buttonSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonScheduleActionPerformed(evt);
            }
        });

        buttonGoals.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        buttonGoals.setText("Goals");
        buttonGoals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGoalsActionPerformed(evt);
            }
        });

        buttonTrainGuide.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        buttonTrainGuide.setText("Training Guide");
        buttonTrainGuide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTrainGuideActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonTrainGuide)
                .addGap(18, 18, 18)
                .addComponent(buttonMaps, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSchedule)
                .addGap(11, 11, 11)
                .addComponent(buttonGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(panelCustome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCustome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonTrainGuide)
                        .addComponent(buttonMaps)
                        .addComponent(buttonSchedule)
                        .addComponent(buttonGoals)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );

        jadwalTerbooking.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jadwalTerbooking.setText("Jadwal Terbooking :");

        jadwalTerbookingFill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(perbaruiDaftarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookingJadwalButton)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelNama)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(namaFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelTrainer)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pelatihFill, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelTingkat)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tingkatFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelDurasi)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(durasiFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelJam)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jamFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(deleteButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jadwalTerbooking)
                        .addGap(18, 18, 18)
                        .addComponent(jadwalTerbookingFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(419, 419, 419))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jadwalTerbooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jadwalTerbookingFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namaFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNama))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelTrainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pelatihFill, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tingkatFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTingkat))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(durasiFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDurasi))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jamFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelJam))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(perbaruiDaftarButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookingJadwalButton)))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookingJadwalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingJadwalButtonMouseClicked
        try {
            if (!selectedJadwalTersedia.isEmpty()) {
                String query = "INSERT INTO dbjadwaluser SELECT * FROM dbjadwal where name = ?";
                java.sql.PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1, selectedJadwalTersedia);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Jadwal berhasil dibooking");
                bookedJadwal++;
                jadwalTerbookingFill.setText(Integer.toString(bookedJadwal));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Jadwal tidak berhasil dibooking");
            System.out.println(e.getMessage());
        }
        selectedJadwalTersedia = null;
        bookingJadwalButton.setVisible(false);
    }//GEN-LAST:event_bookingJadwalButtonMouseClicked

    private void perbaruiDaftarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perbaruiDaftarButtonMouseClicked
        loadJadwalTersedia();
        loadJadwalUser();
    }//GEN-LAST:event_perbaruiDaftarButtonMouseClicked

    private void listJadwalTersediaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listJadwalTersediaMouseClicked
        deleteButton.setVisible(false);
        String selectedNama = listJadwalTersedia.getSelectedValue();
        if (selectedNama != null) {
            try {
                String query = "SELECT * FROM dbjadwal WHERE name = ?";
                PreparedStatement ps = conn.prepareStatement(query);
                ps.setString(1, selectedNama);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    namaFill.setText(rs.getString("name"));
                    pelatihFill.setText(rs.getString("trainer"));
                    tingkatFill.setText(rs.getString("difficulty"));
                    durasiFill.setText(rs.getString("duration"));
                    jamFill.setText(rs.getString("startTime"));
                    selectedJadwalTersedia = rs.getString("name");
                    bookingJadwalButton.setVisible(true);
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_listJadwalTersediaMouseClicked

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        try {
            String query = "DELETE FROM dbjadwaluser WHERE name = ?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1, selectedJadwalUser);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data dihapus!", "Pemberitahuan", JOptionPane.WARNING_MESSAGE);
            loadJadwalUser();
            bookedJadwal--;
            jadwalTerbookingFill.setText(Integer.toString(bookedJadwal));
        } catch (SQLException ex) {
            ex.getMessage();
        }
        selectedJadwalUser = null;
        deleteButton.setVisible(false);
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void listJadwalUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listJadwalUserMouseClicked
        bookingJadwalButton.setVisible(false);
        String selectedNama = listJadwalUser.getSelectedValue();
        if (selectedNama != null) {
            try {
                String query = "SELECT * FROM dbjadwaluser WHERE name = ?";
                PreparedStatement ps = conn.prepareStatement(query);
                ps.setString(1, selectedNama);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    namaFill.setText(rs.getString("name"));
                    pelatihFill.setText(rs.getString("trainer"));
                    tingkatFill.setText(rs.getString("difficulty"));
                    durasiFill.setText(rs.getString("duration"));
                    jamFill.setText(rs.getString("startTime"));
                    deleteButton.setVisible(true);
                    selectedJadwalUser = rs.getString("name");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_listJadwalUserMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    ButtonLogout addForm = new ButtonLogout(Jadwal.this, true);
        addForm.setVisible(true); 
          dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonScheduleActionPerformed
         Jadwal jadwal = new Jadwal();
        jadwal.show();
        dispose();
    }//GEN-LAST:event_buttonScheduleActionPerformed

    private void buttonGoalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGoalsActionPerformed
        // TODO add your handling code here:
        GoalsTest goals = new GoalsTest();
        goals.show();
        dispose();
    }//GEN-LAST:event_buttonGoalsActionPerformed

    private void buttonTrainGuideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTrainGuideActionPerformed
        // TODO add your handling code here:
        TrainingGuide trainGuide = new TrainingGuide();
        trainGuide.show();
        dispose();
    }//GEN-LAST:event_buttonTrainGuideActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void buttonMapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMapsActionPerformed
        // TODO add your handling code here:
        Maps maps = new Maps();
        maps.show();
        dispose();
    }//GEN-LAST:event_buttonMapsActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
         DashboardMember dbTrainer = new DashboardMember();
        dbTrainer.show();
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jadwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookingJadwalButton;
    private javax.swing.JButton buttonGoals;
    private javax.swing.JButton buttonMaps;
    private javax.swing.JButton buttonSchedule;
    private javax.swing.JButton buttonTrainGuide;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel durasiFill;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jadwalTerbooking;
    private javax.swing.JLabel jadwalTerbookingFill;
    private javax.swing.JLabel jamFill;
    private javax.swing.JLabel labelDurasi;
    private javax.swing.JLabel labelJam;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelTingkat;
    private javax.swing.JLabel labelTrainer;
    private javax.swing.JList<String> listJadwalTersedia;
    private javax.swing.JList<String> listJadwalUser;
    private javax.swing.JLabel namaFill;
    private Custome.PanelCustome panelCustome2;
    private javax.swing.JLabel pelatihFill;
    private javax.swing.JButton perbaruiDaftarButton;
    private javax.swing.JLabel tingkatFill;
    // End of variables declaration//GEN-END:variables
}
